services:
  alist:
    image: xhofe/alist:v3.52.0-ffmpeg
    container_name: alist
    volumes:
      - /data/disk2t/alist:/opt/alist/data
      - /data/disk2t/HomeCloud:/HomeCloud/disk2t
      - /data/disk4t/HomeCloud:/HomeCloud/disk4t
    ports:
      - 8100:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: unless-stopped
